### ISSUE TITLE
Hi Jummy

### ISSUE THREAD

**Issue by yizhiheng** [JummyHuang/Currency#1]
你好, 看了你的app绝对创意挺不错的...看了一下还没有完善实时汇率的功能对吧?
有兴趣做好以后发app store吗? 如果有的话我挺愿意和你协作开发一个完整的app的

**Comment by JummyHuang** [comment]
嗯，我本来也打算边学习边完善整个App，最后当然希望登陆到App Store中，如果你感兴趣的话欢迎一起讨论，互相学习。

**Comment by JummyHuang** [comment]
你好，我现在邀请你和我一起完成这个App，最后希望我们能将它在App store 中发布，请问你有意愿吗？
